name: deploy

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'The optional name of the artifact to build and deploy the dashboard from'
        required: false
        type: string
        default: 'dashboard'
      configuration-url:
        description: 'The URL of the configuration file to use for the dashboard'
        required: true
        type: string
      deploy:
        description: 'Whether to deploy the dashboard after building it'
        required: false
        type: boolean
        default: ${{ github.ref_name == github.event.repository.default_branch }}
      environment:
        description: 'The GitHub environment to deploy the dashboard to'
        required: false
        type: string
        default: 'github-pages'
      ref:
        description: 'The optional reference of the repository to build and deploy the dashboard from'
        required: false
        type: string
        default: 'main'
      repository:
        description: 'The optional full name of the repository to build and deploy the dashboard from'
        required: false
        type: string
        default: 'martincostello/benchmarks-dashboard'
      runs-on:
        description: 'The optional type of runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'

permissions: {}

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  FORCE_COLOR: 3
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 20

    permissions:
      contents: read

    steps:

    - name: Update Windows agent configuration
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        "DOTNET_INSTALL_DIR=D:\tools\dotnet" >> ${env:GITHUB_ENV}
        "DOTNET_ROOT=D:\tools\dotnet" >> ${env:GITHUB_ENV}
        "NUGET_PACKAGES=D:\.nuget\packages" >> ${env:GITHUB_ENV}

    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        filter: 'tree:0'
        persist-credentials: false
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        show-progress: false

    - name: Overwrite configuration file
      shell: pwsh
      env:
        CONFIGURATION_URL: ${{ inputs.configuration-url }}
      run: |
        $configFilePath = Join-Path ${env:GITHUB_WORKSPACE} "src/Dashboard/wwwroot/appsettings.json"
        Invoke-WebRequest -Uri ${env:CONFIGURATION_URL} -OutFile $configFilePath -UseBasicParsing | Out-Null

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1

    - name: Install .NET WASM tools
      run: dotnet workload install wasm-tools

    - name: Build, Test and Publish
      run: ./build.ps1 -SkipTests

    - name: Publish dashboard
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{ inputs.artifact-name }}
        path: ./artifacts/publish/Dashboard/release/wwwroot
        if-no-files-found: error

  deploy:
    needs: [ build ]
    runs-on: ${{ inputs.runs-on }}
    if: ${{ inputs.deploy == true }}

    concurrency:
      group: ${{ inputs.environment }}
      cancel-in-progress: false

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      id-token: write
      pages: write

    steps:

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          filter: 'tree:0'
          persist-credentials: false
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          show-progress: false

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Download dashboard artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: dashboard

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: dashboard

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
